services:
  todo-front-dev:
    build:
      context: ./todo-frontend/
      dockerfile: Dockerfile
      target: dev
    volumes:
      - ./todo-frontend:/usr/src/app
    environment:
      VITE_BACKEND_URL: http://localhost:8080/api/
    container_name: todo-front-dev

  mongo-dev:
    image: mongo
    ports:
      - 3456:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: the_database
    volumes:
      - ./todo-backend/mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
      - ./todo-backend/mongo/data/dev:/data/db

  redis-dev:
    image: redis
    command: ['redis-server', '--appendonly', 'yes']
    ports:
      - 6379:6379
    volumes:
      - ./todo-backend/redis/data/dev:/data

  todo-server-dev:
    build:
      context: ./todo-backend/
      dockerfile: Dockerfile
      target: dev
    ports:
      - 3000:3000
    container_name: todo-server-dev
    environment:
      MONGO_URL: mongodb://the_username:the_password@mongo-dev:27017/the_database
      REDIS_URL: redis://redis-dev:6379
    depends_on:
      - mongo-dev
      - redis-dev

  todo-nginx-dev:
    image: nginx:1.20.1
    volumes:
      - ./nginx.dev.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:80
    container_name: todo-nginx-dev
    depends_on:
      - todo-front-dev
      - todo-server-dev