services:
  app:
    build:
      context: ./library-frontend
      dockerfile: Dockerfile
      target: prod
    volumes:
      - ./library-frontend:/usr/src/app
    ports:
      - 3000:3000
    container_name: app

  server:
    build:
      context: ./library-backend
      dockerfile: Dockerfile
      target: prod
    volumes:
      - ./library-backend:/usr/src/server
    ports:
      - 4001:4001
    container_name: server

  nginx:
    image: nginx:1.20.1
    ports:
      - 8080:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    container_name: reverse-proxy
    depends_on:
      - server
      - app
